import './globals.css';
import type {Metadata} from 'next';
import {Open_Sans} from 'next/font/google';
import { Header } from './components/Header/Header';

const noto = Open_Sans({
  variable: '--font-open',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'My Project',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ru">
      <body className={noto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
